AUTHOR_ID  = CROMU
SERVICE_ID = 00013
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_SEED = 843486633
POLLS_TESTING_SEED = -1294433035

include /usr/share/cb-testing/cgc-cb.mk
